@startuml
skinparam ComponentStyle rectangle
skinparam Component {
    ' FontSize 200
    ' BackgroundColor transparent
    ' BorderColor black
    ' BorderThickness 10
}
rectangle rr2 {
    [single page]
    [move_freepages_block()]
    [move_freepages()]

    [move_freepages_block()]-down->[move_freepages()]
}

rectangle rr1 {
    rectangle "Loop(max_order ~ min_order)" as r1 {
        component "find_suitalbe_fallback()" as fsf1
    }

    component "steal_suitable_fallback()" as ssf

    rectangle "Loop(order ~ - max_order)" as r2 {
        component "find_suitalbe_fallback()" as fsf2
    }

    r1-down[hidden].ssf
    ssf-down[hidden].r2

    ssf<-up-fsf1
    ssf<-down-fsf2
}

ssf-up->[single page]
ssf-down->[move_freepages_block()]



@enduml