@startuml
scale 4096x4096
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 100
    BorderColor black
    BorderThickness 5
}

skinparam ArrowThickness 5

skinparam Rectangle {
    FontSize 0
    BorderColor transparent
}

rectangle {
    [tag1] $tag1
    [rmqueue()] #DarkOrange
    [tag2] $tag2

    [tag1]-down-[rmqueue()]
    [rmqueue()]-down----------[tag2]
    hide $tag1
    hide $tag2
}

rectangle {
    [rmqueue_pcplist()] #LightSalmon
    [__rmqueue_smallest()] #LightSalmon
    [__rmqueue()] #LightSalmon
    [tag3] $tag3

    [rmqueue_pcplist()]-down[hidden]--[__rmqueue_smallest()]
    [__rmqueue_smallest()]-down.[__rmqueue()]
    [__rmqueue()]-down-------[tag3]
    hide $tag3
}

[rmqueue()]-up-|>[rmqueue_pcplist()]
[rmqueue()]-down-|>[__rmqueue_smallest()]

rectangle {
    [tag4] $tag4
    component "__rmqueue_smallest()" as rsmall #LightSalmon
    [__rmqueue_cma_fallback()] #LightSalmon
    [__rmqueue_fallback()] #LightSalmon
    [tag5] $tag5

    [tag4]-down----rsmall
    rsmall-down.[__rmqueue_cma_fallback()]
    [__rmqueue_cma_fallback()]-down.[__rmqueue_fallback()]
    hide $tag4
    [__rmqueue_fallback()]-down-----[tag5]
    hide $tag5
}

[__rmqueue()]-->[rsmall]

rectangle {
    component "for(max order ~ min order)\t" as nofrag #LightBlue {
        component "find_suitable_fallback()" as fsf1
    }

    component "for (order ~ -max_order)\t\t" as frag #LightBlue {
        component "find_suitable_fallback()" as fsf2
    }

    [tag6] $tag6

    nofrag-down[hidden]--frag
    fsf1-.>fsf2
    fsf2-down...[tag6]
    hide $tag6
}

[__rmqueue_fallback()]-->nofrag

rectangle {
    component "steal_suitable_fallback()" as ssf
    [tag7] $tag7
    
    ssf-down--[tag7]
    hide $tag7
}

fsf1-->ssf
fsf2-->ssf

rectangle {
    [single page]
    [move_freepages_block()]
    [move_freepages()]
    [tag8] $tag8

    [single page]-down[hidden]-[move_freepages_block()]
    [move_freepages_block()]-down->[move_freepages()]
    [move_freepages()]-down-[tag8]
    hide $tag8
}

ssf-up->[single page]
ssf-->[move_freepages_block()]

@enduml