@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5
skinparam RoundCorner 100

skinparam Component {
    FontSize 200
    FontColor black
    BorderThickness 10
    BackgroundColor LightGrey
}

component "  move to unevictable  " as cp

@enduml
