@startuml
scale 1/1
left to right direction
skinparam Component {
    FontSize 20
    BorderThickness 1
}
skinparam ComponentStyle rectangle
skinparam Package {
    FontSize 20
    BorderThickness 0
}

package "Mappings" as p1 #LemonChiffon {
    component "task A" as a1
    component "task B" as b1
    component "page table" as pt1
    component "page table" as pt2
    component "shared page" as sp1 #LightGreen

    [a1]....>[pt1] : virtual address
    [b1]....>[pt2] : virtual address
    [pt1]...>[sp1] : physical address
    [pt2]...>[sp1] : physical address
}

@enduml