@startuml
scale 1/1
left to right direction
skinparam Component {
    FontSize 20
    BorderThickness 1
}
skinparam ComponentStyle rectangle
skinparam Package {
    FontSize 20
    BorderThickness 0
}

package "Reverse Mappings" as p2 #LightBlue {
    [rmap]
    component "task A" as a2
    component "task B" as b2
    component "shared page" as sp2 #LightGreen

    [sp2].....>[rmap] : physical address
    [rmap]...>[a2] : virtual address
    [rmap]...>[b2] : virtual address
}

@enduml