@startuml
title __alloc_pages_direct_compact()

:psi_memstall_enter(&pflags);
:delayacct_compact_start();
:noreclaim_flag = memalloc_noreclaim_save();
note left
    we need to allocate twice as much
    memory as the requested order to
    perform the direct-compaction, but
    since we are currently out of memory,
    we use the pfmemalloc flag on the
    current task to set the memory allocation
    without watermark restrictions.
end note
:try_to_compact_pages();
:memalloc_noreclaim_restore(noreclaim_flag);
:psi_memstall_leave(&pflags);
:delayacct_compact_end();

if (COMPACT_SKIPPED ?) then (Yes)
    :return NULL;
    detach
endif
:count_vm_event(COMPACTSTALL);
if (page) then (Yes)
    :prep_new_page();
    note left
        Prep a captured page if available
    end note
endif
:get_page_from_freelist();
if (get page ?) then (Yes)
    :compaction_defer_reset();
    :return page;
    detach
endif
:return NULL;

@enduml