@startuml
title __compact_finished

if (compact_scanners_met()) then (Yes)
    :reset_cached_positions();
    if (scanned whole zone) then (Yes)
        :return COMPACT_COMPLETE;
    else (No)
        :return COMPACT_PARTIAL_SKIP;
    endif
    detach
endif

if (kcompactd ?) then (Yes)
    if (kswapd is running?) then (Yes)
        :return COMPACT_PARTIAL_SKIP;
        detach
    endif
    :fragmentation_score_zone();
    :fragmentation_score_wmark();
    if (score > wmark_low) then (Yes)
        :return COMPACT_CONTINUE;
    else (No)
        :return COMPACT_SUCCESS;
    endif
    detach
endif

if (manual) then (Yes)
    :return COMPACT_CONTINUE;
    detach
endif
note left:/proc/sys/vm/compact_memory

if (pageblock_aligned()) then (No)
    :return COMPACT_CONTINUE;
    detach
endif

while (for loop order~MAX_ORDER)
    if (free_area_empty()) then (Yes)
        :return COMPACT_SUCCESS;
        detach
    endif
    if (movable) then (Yes)
        :return COMPACT_SUCCESS;
        detach
    endif
    if (find_suitable_fallback()) then (Yes)
        :return COMPACT_SUCCESS;
        detach
    endif
    note left
    if there is a free page to be
    imported from another type, it
    returns COMPACT_SUCCESS if it
    is of movable type.
    end note
    :Backward;
endwhile
:return ret;

@enduml