@startuml
scale 1/5

skinparam Component {
    Style rectangle
    FontSize 200
    BorderThickness 10
    BackgroundColor transparent
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderThickness 0
}

[  struct page  ] #SkyBlue

@enduml