@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5
skinparam RoundCorner 100

skinparam Component {
    FontSize 200
    FontColor black
    RoundCorner 10
    BorderThickness 10
    BackgroundColor transparent
    BorderThickness<<text>> 0
    BackgroundColor<<text>> transparent
    FontColor<<box>> transparent
}

component "  <b>pgdat->kswapd_wait  " as cp

@enduml
