@startuml
title should_compact_retry()

start
if (order == 0) then (Yes)
    :return false;
    detach
endif

if (fatal_signal_pending(current)) then (Yes)
    :return false;
    detach
endif
if (result == COMPACT_SUCESS) then (Yes)
    :compaction_retries++;
endif

if (result == COMPACT_COMPLETE) then (Yes)
    :goto check_priority;<<output>>
    detach
endif
if (compaction_needs_reclaim()) then (Yes)
	:compaction_zonelist_suitable();
	:goto out;<<output>>
    detach
endif
if (result == (COMPACT_DEFERED\n|| COMPACT_CONTENTED\n|| COMPACT_PARTIAL_SKIP)) then (Yes)
    :goto check_priority;<<output>>
    detach
endif
:compact retries checking;
#Orange:check_priority;<<input>>
:attempts at the highest priority;
#Orange:out;<<input>>
:return ret;

stop

@enduml