@startuml
title should_reclaim_retry()

start
note left
Checks whether it makes sense to retry the reclaim to make a forward progress
for the given allocation request.

We give up when we either have tried MAX_RECLAIM_RETRIES in a row
without success, or when we couldn't even meet the watermark if we
reclaimed all remaining pages on the LRU lists.

Returns true if a retry is viable or false to enter the oom path.
end note

stop

@enduml