#
title = "shrink_active_list()"
color_list = ["LightGreen", "LightGrey", "LightYellow", "White", "Pink", "Black", "Blue"]

[[lists]]

name = "active_lru"
data = ["PG", "PG", "PG"]
color_map = [0, 3, 1]
layout = [0, 0, 1, 1, 0, 2, 1, 1]

[[lists]]

name = "isolation"
data = ["PG", "PG", "PG", "PG", "PG"]
color_map = [1, 0, 3, 2, 4]

[[lists]]

name = "inactive_lru"
data = ["PG", "PG", "PG"]
color_map = [4, 3, 1]
layout = [0, 0, 1, 0, 0, 2, 0, 1, 0, 0]

[[texts]]

name = "lru"
data = [
    "shrink_active_list()",
    "(anon/file) active lru",
    "(anon/file) inactive lru",
    "**buddy free**",
    "PGDEACTIVATE++",
]
color_map = [5, 5, 5, 5, 6]

[[blocks]]

name = "lru_pages"
data = [
    "  unevictable page\\t\\t",
    "  exec referred page\\t",
    "  other referred page\\t",
    "  non-user page\\t",
    "  other page\\t",
]
color_map = [1, 0, 2, 4, 3]
layout = [[0, 3], [1, 4], [2]]
