@startuml
skinparam ComponentStyle rectangle
'skinparam DefaultFontName Monospace Regular
'header page1
'footer some footer

title memcg/node lruvecs

caption Figure memcg/node lruvecs

rectangle "node_data[]" as nodes {
    component "\t\tnode #0\t\t" as cp1
    component "\t\tnode #N\t\t" as cp2

    cp1-down.cp2
}

component "lruvec" as lv1 #GreenYellow
component "lruvec" as lv2 #GreenYellow

cp1-right->lv1
cp2-right->lv2

component lvt1 [
    LRU_INACTIVE_ANON
    ----
    LRU_ACTIVE_ANON
    ----
    LRU_INACTIVE_FILE
    ----
    LRU_ACTIVE_FILE
    ----
    LRU_UNEVICTABLE
]

component lvt2 [
    LRU_INACTIVE_ANON
    ----
    LRU_ACTIVE_ANON
    ----
    LRU_INACTIVE_FILE
    ----
    LRU_ACTIVE_FILE
    ----
    LRU_UNEVICTABLE
]

lv1-right->lvt1
lv2-right->lvt2

rectangle "/sys/fs/cgroup/memory" as memcg {
    component root [
        memcg (/)
    ]
    component grp1 [
        memcg (/grp1)
    ]
    component grp2 [
        memcg (/grp2)
    ]
    component grp1a [
        memcg (/grp1/a)
    ]
    component grp1b [
        memcg (/grp1/b)
    ]

    root-->grp1
    root-->grp2
    grp1-->grp1a
    grp1-->grp1b
}

grp2-->nodes : **memcg->nodeinfo[]**

@enduml