@startuml

skinparam ComponentStyle rectangle
hide stereotype
left to right direction
scale 1/1

skinparam Component {
    FontSize 40
    FontColor black
    RoundCorner 10
    BorderThickness 2
    BackgroundColor transparent
    BorderThickness<<text>> 0
    BackgroundColor<<text>> transparent
    FontColor<<box>> transparent
}


skinparam Interface {
    FontSize 0
    FontColor black
    RoundCorner 10
    BorderThickness 0
    BackgroundColor transparent
    BorderThickness<<text>> 0
    BackgroundColor<<text>> transparent
    FontColor<<box>> transparent
}

skinparam ArrowThickness 2
' components:
interface "o" as head
component "PG" as c0 #LightBlue
component "PG" as c1 #LightBlue
component "PG" as c2 #LightBlue
component "PG" as c3 #LightBlue
interface "o" as tail
' layout:
head-down.c0
c0-down.c1
c1-down.c2
c2-down.c3
c3-down.tail

@enduml
