@startuml
skinparam ComponentStyle rectangle
skinparam NoteBorderColor white
skinparam NoteBackgroundColor pink
skinparam NoteShadowing true
'skinparam Linetype ortho
skinparam rectangle {
    BorderColor white 
    FontColor white
    FontSize 0
}

title Isolation Function Calls

[compact_zone()] #OrangeRed
note left of [compact_zone()]
1) Compaction
* direct
* manual
* background (kcompactd)
end note

rectangle r1 {
    [migrate_pages()]
    [compaction_alloc()]

    [migrate_pages()]-->[compaction_alloc()]
}

rectangle r2 {
    [isolate_migratepages()]
    [isolate_freepages()]

    '[isolate_migratepages()]-left[hidden]-[isolate_freepages()]
}

rectangle r3 {
    [isolate_migratepages_block()]
    [isolate_freepages_block()]
}

rectangle r4 {
    [__isolate_lru_page()]
    [isolate_movable_page()]
    [__isolate_free_page()]
}

rectangle r5 {
    [isolate_migratepages_range()]
    [isolate_freepages_range()]
}

[do_migrate_range()] #OrangeRed
note left of [do_migrate_range()]
3) Off-line Memory (Hot-plug Memory)
end note

[alloc_contig_range()] #OrangeRed
note right of [alloc_contig_range()]
2) CMA
end note

r5-up[hidden]-r4

[compact_zone()]-->[isolate_migratepages()] :**for LRU**
[compact_zone()]-->[migrate_pages()]
[compaction_alloc()]-->[isolate_freepages()]

[isolate_migratepages()]-->[isolate_migratepages_block()]
[isolate_freepages()]-->[isolate_freepages_block()]

[isolate_migratepages_block()]-->[__isolate_lru_page()]
[isolate_freepages_block()]-->[__isolate_free_page()]
[compact_zone()]-->[isolate_movable_page()] :**for non-LRU**

[isolate_freepages_range()]-up->[isolate_freepages_block()]
[isolate_migratepages_range()]-up->[isolate_migratepages_block()]

[do_migrate_range()]-up->[isolate_movable_page()]
[do_migrate_range()]-down->[alloc from buddy system]

[__alloc_contig_range()]-up->[isolate_migratepages_range()]
[alloc_contig_range()]-up->[__alloc_contig_range()]
[alloc_contig_range()]-up->[isolate_freepages_range()]



@enduml