@startuml
skinparam ComponentStyle rectangle
skinparam RectangleBorderColor transparent
'left to right direction

title Scanners for Compaction

rectangle ZONE_NORMAL {
    component "     page_block     " as pb1 #OrangeRed
    component "     page_block     " as pb2
    component "     page_block     " as pb3
    component "     page_block     " as pb4
    component "     page_block     " as pb5 #GreenYellow

    pb1-right[hidden]-pb2
    pb2-right[hidden]-pb3
    pb3-right[hidden]-pb4
    pb4-right[hidden]-pb5
}

rectangle {
    component zone_start [
    zone->start_pfn
    ----
    cc->migrate_pfn
    ----
    zone->compact_cached_migrate_pfn[]
    ]

    component "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" as sep1 $tag1

    component zone_end [
    zone->end_pfn
    ----
    cc->free_pfn
    ----
    zone->compact_cached_free_pfn
    ]

    zone_start-right-sep1
    zone_end-left-sep1
    hide $tag1
}

rectangle {
    [isolate_migratepages()]
    [x] #transparent
    [isolate_freepages()]
    [isolate_migratepages_block()]
    [isolate_freepages_block()]

    [isolate_migratepages()]-right->[isolate_migratepages_block()]
    [isolate_freepages()]-left->[isolate_freepages_block()]

    [isolate_migratepages_block()].right.>[x]
    [isolate_freepages_block()].left.>[x]
}


pb1<-up-[zone_start]
pb5<-up-[zone_end]

pb1-down->[isolate_migratepages()]
pb5-down->[isolate_freepages()]


@enduml