@startuml
title __do_kmalloc_node

start
:get minalign;

if (size < PAGE_SIZE) then (Yes)
    :slob_alloc;
    note left:fast path
else
    :slob_new_pages;
    note right:slow path
endif

end

@enduml