@startuml
title slob_alloc

start
:get slob_list;
note left
if 0 < size + minalign < 256
    slob_list = free_slob_small
elif 256 < size + minalign < 1024
    slob_list = free_slob_medium
elif 1024 < size + minalign < PAGE_SIZE
    slob_list = free_slob_large
end note

stop
@enduml