@startuml

scale 2/1
left to right direction
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 20
    BackgroundColor LightBlue
    BorderThickness 1.5
    BorderColor black
}

skinparam Package {
    FontSize 20
    BackgroundColor transparent
    BorderThickness 0
}

package "PCP (Per-CPU page frame cache)" as p1 {
    component "  pcp->lists[MIGRATE_UNMOVABLE]\t\t\t\t  " as c1 #LightYellow
    component "page" as c2 #Lightgrey
    component "page" as c3 #Lightgrey
    component " 1 " as c4
    component " 2 " as c5
    component " 3 " as c6

    [c1]-down.[c2]
    [c2]-down.[c3]
    [c3]-down.[c4]
    [c4]-down.[c5]
    [c5]-down.[c6]
}

@enduml