@startuml
scale 2/1
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 20
    BackgroundColor tansparent
    BorderThickness 0
    BorderColor black
}

component c1 [
    **case A) dirty size**
    /proc/sys/vm/dirty_bytes=2,147,483,648 (2G)
]

component "xxx\t\t\t\t" as tag0 $tag0

component c2 [
    **node_dirty_limit(n0)** = 2G * 4G / 10G = 210,944 pages (0.8G)
    **node_dirty_limit(n1)** = 2G * 6G / 10G = 313,344 pages (1.2G)
]

c1-right-[tag0]
[tag0]-right-[c2]
hide $tag0

@enduml