@startuml

title kcompactd()

start

:set cpuset mask;
:set_freezable();
:reset the maximum order
and zone of kcompactd;
while (!kthread_should_stop())
    if (wait_event_freezable_timeout() &&
    !pgdat->proactive_compact_trigger) then (Yes)
	    :psi_memstall_enter(&pflags);
	    :kcompactd_do_work(pgdat);
	    :psi_memstall_leave(&pflags);
        :Reset timeout value;
        :continue;
        detach
    endif
    :Start the proactive work with default timeout.
    Based on the fragmentation score, this timeout
    is updated;
endwhile

stop

@enduml