@startuml

title kswapd()

start
:set cpumask of node;
:tsk->flags |= PF_MEMALLOC | PF_KSWAPD;
:set_freezable();
:pgdat settings;
note left
    * kswpd_order
    * kswapd_highest_zoneidx
    * nr_writeback_throttled
end note
while ()
    :get kswapd_order;
    :get highest_zoneidx;
    #OrangeRed :kswapd_try_to_sleep();
    :read the new order
    and highest_zoneidx;
    :ret = try_to_freeze();
    if (kthread_should_stop()) then (Yes)
        break
    endif
    if (ret > 0) then (Yes)
    :continue;
    note left
        continue without running the
        node balance for faster processing
    end note
    detach
    endif
    :balance_pgdat();
endwhile

stop

@enduml