@startuml
skinparam Shadowing true
'skinparam Handwritten true
skinparam Component {
    Style rectangle
    FontSize 20
    FontColor black
}
skinparam rectangle {
    BorderColor transparent
    FontColor transparent
    FontSize 0
}

title shrink_zones()

[shrink_node()]

rectangle r1 {
    [shrink_zones()]
    [tag1] $tag1

    [shrink_zones()]-.......[tag1]
    hide $tag1
}

rectangle r2 {
    [shrink_node_memcgs()]
    [shrink_lruvec()]
    [shrink_slab()]
    [tag2] $tag2

    [shrink_node_memcgs()]-.[shrink_lruvec()]
    [shrink_lruvec()]-.[shrink_slab()]
    [shrink_slab()]-->[do_shrink_slab()]
    [do_shrink_slab()]-....>[tag2]
    hide $tag2
}

rectangle r3 {
    [shrink_list()]
    [shrink_active_list()]
    [shrink_inactive_list()]

    [shrink_list()]-up.[shrink_active_list()]
    [shrink_list()]-down.[shrink_inactive_list()]
    [shrink_inactive_list()]-->[shrink_folio_list()]
}

rectangle r41 {
    component "rotate to active" as rta
    component "move to unevictable" as mtu
    component "move to inactive" as mti
    component "buddy free" as bf1
}

rectangle {
card ANON #SkyBlue {
    [add_to_swap()]
    [get_swap_page()]
    [add_to_swap_cache()]
    [__add_to_swap_cache()]

    [add_to_swap()]-->[get_swap_page()]
    [get_swap_page()]-->[add_to_swap_cache()]
    [add_to_swap_cache()]-->[__add_to_swap_cache()]

}

card FILE #LightGrey {
    [page_out()]
    component "mapping->a_ops->writepage()" as writepage
    [page_out()]-->[writepage]
}

rectangle r44 {
    component "rotate to inactive" as rti
    component "buddy free" as bf2
}
}

r41-down[hidden]--r3

' layout
r1-right[hidden]-r2
r2-right[hidden]-r3

[shrink_zones()]-->[shrink_node()]

[shrink_node()]-down->[shrink_node_memcgs()]

[shrink_lruvec()]-->[shrink_list()]

[shrink_active_list()]-up->[rta]
[shrink_active_list()]-up->[mtu]
[shrink_active_list()]-up->[mti]
[shrink_active_list()]-up->[bf1]

[shrink_folio_list()]-->[add_to_swap()]
[shrink_folio_list()]-->[page_out()]

[shrink_folio_list()]-->[rti]
[shrink_folio_list()]-->[bf2]


@enduml
