@startuml

skinparam ComponentStyle rectangle
scale 1/5

skinparam Component {
    FontSize 200
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}

component "lruvec" as cp #LightGreen

@enduml
