title = "your title"
color_list = [
    "transparent", #0
    "black",       #1
    "blue",        #2
    "gold",        #3
    "green",       #4
    "pink",        #5
    "red",         #6
    "white",       #7
    "LightBlue",   #8
    "LightGreen",  #9
    "LightGrey",   #10
    "LightYellow", #11
]

[[bitmaps]]

name = "swap_entry_t_32"
data = [[0, 31]]
color_map = [10]
