@startuml
title __rmqueue()

start
if (alloc & ALLOC_CMA && zone_page_state(zone, NR_FREE_CMA_PAGES) >
zone_page_state(zone, NR_FREE_PAGES) / 2) then
:__rmqueue_cma_fallback();
endif
#Orange:retry;<<input>>
if (!__rmqueue_smallest())
if (alloc & ALLOC_CMA)
    :__rmqueue_cma_fallback();
endif
:__rmqueue_fallback();
endif

:return page;
stop

@enduml