@startuml
title rmqueue_buddy()

start
repeat
    if (order > 0 && alloc_flags & ALLOC_HARDER)
        :page = __rmqueue_smallest();
        if (!page)
            :page = __rmqueue();
        endif
    endif
repeat while (check_new_pages())
:return page;
stop

@enduml