@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 2/1

skinparam Activity {
    FontSize 20
    FontColor black
    BorderThickness 1.2
    BackgroundColor transparent
}

skinparam ActivityFontColor<<hide>> transparent
skinparam ActivityBorderThickness<<hide>> 0

skinparam Note {
    FontSize 16
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}


skinparam Arrow {
    FontSize 16
    FontColor black
    BorderThickness 1.2
    BackgroundColor transparent
}

' start here
#OrangeRed:shrink_inactive_list();
#LightYellow:lru_add_drain();
#LightYellow:isolate_lru_pages();
#LightYellow:shrink_page_list();
#LightYellow:putback_inactive_pages();
#LightYellow:free_hot_cold_page_list();
:return;<<hide>>

@enduml
