#
title = "__kmem_cache_alias()"
color_list = [
    "Black",       #0
    "Blue",        #1
    "LightBlue",   #2
    "LightYellow", #3
]

[[textboxes]]

data = ["slab_caches", "alias_list", "kmem_cache"]
color_map = [3, 3, 2]

[[texts]]

data = ["""merged condition:
    * size is equal
    * align is equal
    * not use <color:Yellow>SLAB_NEVER_MERGE
    * use <color:Green>SLAB_MERGE_SAME""",
    "<b>__kmem_cache_alias()",
]
color_map = [0, 0]

[[tables]]

data = """
| .name | jbd2_revoke_record_s |
|<#LightYellow> .flags | *a |
|<#LightYellow> .size | 32 |
|<#LightYellow> .align | 8 |
| .cpu_partial | 30 |
| .min_partial | 5 |
| .reserved | 0 |
| .offset | 0 |
| .refcount | 2 |
| .inuse | |
| .objects | 95488 |
| .oo.x[31:16] | 0 |
| .oo.x[15:0] | 128 |"""

[[tables]]

data = """
| .name | jbd2_journal_handle |
|<#LightYellow> .flags | *a |
|<#LightYellow> .size | 32 |
|<#LightYellow> .align | 8 |"""
