@startuml
title __alloc_pages_direct_compact()

:try_to_compact_pages();
if (COMPACT_SKIPPED ?) then (Yes)
    :return NULL;
    detach
endif
:get_page_from_freelist();
if (get page ?) then (Yes)
    :compaction_defer_reset();
    :return page;
    detach
endif
:return NULL;

@enduml