@startuml
skinparam ComponentStyle rectangle
skinparam NoteBorderColor white
skinparam NoteBackgroundColor pink
skinparam NoteShadowing true
'skinparam Linetype ortho
skinparam rectangle {
    BorderColor white 
}

title Direct Compaction Function Flow 

card __alloc_pages_slowpath {
    [__alloc_pages_direct_compact()] #Darkorange
    [get_page_from_freelist()]

    [__alloc_pages_direct_compact()]-down[hidden]-[get_page_from_freelist()]
}

rectangle {
    [try_to_compact_pages()] #Darkorange
    [compact_zone_order()] #Darkorange

    [try_to_compact_pages()]-->[compact_zone_order()]
}

card compact_zone() {
    package "while compact_finished()" {
        [isolate_migratepages()]
        [migrate_pages()]

        [isolate_migratepages()]-[hidden]-[migrate_pages()]
    }
}

card unmap_and_move() {
    [compaction_alloc()]
    [__unmap_and_move()]
    [compaction_free()]

    [compaction_alloc()]-[hidden]-[__unmap_and_move()]
    [__unmap_and_move()]-[hidden]-[compaction_free()]
}

card isolate_freepages_block() {
    [split_free_page()]
}

[__alloc_pages_direct_compact()]-->[try_to_compact_pages()]
[compact_zone_order()]-->[compact_zone()]
[isolate_migratepages()]-->[isolate_migratepages_block()]
[migrate_pages()]-->[unmap_and_move()]
[compaction_alloc()]-->[isolate_freepages()]
[isolate_freepages()]-->[isolate_freepages_block()]


@enduml