@startuml
scale 1/1
left to right direction
skinparam Component {
    FontSize 20
    BorderThickness 1
}
skinparam ComponentStyle rectangle
skinparam Package {
    FontSize 20
    BorderThickness 0
}

'skinparam ArrowFontSize 20

package "Request Memory" #LightBlue {
    component "User Task" as ut1 #GreenYellow
    component "VMA" as v1 #LightYellow
    [tag1] $tag1

    [ut1]--->[v1] : request memory
    [v1]------------[tag1]
    hide $tag1
}

@enduml