@startuml

title do_shrink_slab()

start

:get batch_size;
:get the number of free objects;
if (no freeable objects) then (Yes)
    :return;
    detach
endif
:xchg_nr_deferred();
note left
    copy the current shrinker scan count
    into a local variable and zero it so
    that other concurrent shrinker invocations
    don't also do this scanning work.
end note
:calculate delta value;
:calculate total_scan value;
while (total_scan >= batch_size\n|| total_scan >= freeable)
    :nr_to_scan = min(batch_size, total_scan);
    :ret = shrinker->scan_objects();
    if (ret == SHRINK_STOP) then (Yes)
        break
    endif
    :cond_resched();
endwhile
:handle deferred objects;
:return number of freed objects;

stop

@enduml