@startuml
skinparam ActivityFontSize 16
title shrink_lruvec

start

if (lru_gen_enabled()) then (Yes)
    :lru_gen_shrink_lruvec();
    :return;
    detach
endif
:get_scan_count();
note left
    the balance is taken into account
    and the percentage of pages to be
    scanned is calculated.
end note
:check proportional_reclaim;
note left
    If scan_adjusted is set to true,
    the scan ratio of the anon to file
    pages is not rebalanced.
end note
while (inactive anon || active file || inactive file)

    while (for_each_evictable_lru())
        :scan number (max 32) pages;
        :shrink_list();
        note left:reclaim number pages
    endwhile

    :cond_resched();
    if (!nr_file || !nr_anon) then (Yes)
        break
    endif
    if (scanned nr_file > nr_anon) then (Yes)
        :calculates the percentage
        of remaining ANON pages;
    else (No)
        :calculates the percentage
        of remaining FILE pages;
    endif
    :Recalculate the other (ACTIVE) LRU scan count;
    endwhile

:account sc->nr_reclaimed;
if (can_age_anon_pages() && inactive_is_low()) then
    :shrink_active_list();
endif
note left
Even if we did not try to evict anon pages at all,
we want to rebalance the anon lru active/inactive
ratio.
end note

    stop
    @enduml