@startuml

title Active diagram of shrink_zones()

start
if (buffer_heads_over_limit?) then (Yes)
    :scan HIGHMEM zone;
    note left
        highmem pages could be pinning
        lowmem pages storing buffer_heads
    end note
endif

while (for_each_zone_zonelist_nodemask)
    if (!cgroup_reclaim()?) then (Yes)
        if (!cpuset_zone_allowed(GFP_KERNEL | __GFP_HARDWALL)?) then (Yes)
            :Continue;
            detach
        endif
        if (compaction_ready()?) then (Yes)
            :Continue;
            detach
        endif
        :steals pages from memory
        cgroups over softlimit;
    endif
    :shrink_node();
endwhile
:consider_reclaim_throttle(first_pgdat, sc);

stop

@enduml