@startuml
title shrink_active_list

start
:LIST_HEAD(l_hold)
----
LIST_HEAD(l_active)
----
LIST_HEAD(l_inactive);

:lru_add_drain();
note left
    empty the per cpu lrus and
    revert them back to lruvec.
end note
:isolate_lru_folios();
note right:l_hold filled
:__mod_node_page_state;

while (!list_empty(&**l_hold**))
    :cond_resched();
    :**folio** = lru_to_folio(&**l_hold**)
	list_del(&folio->lru);

    if (folio_referenced(**folio**)) then
    note left
        increment the nr_rotate counter
        by the number of pages. And if
        it's an executable cache, move
        it to l_active to rotate it to
        active LRU.
    end note
        :Add VM_EXEC file pages to <color:red>**l_active**;
        :continue;
        detach
    endif
    :deactivate **folio**
    set working_set flag
    and add it to **l_inactive**;

endwhile
:Move folios back to the lru list;
:Keep all free folios in l_active list;
:revert all the pages in the
l_hold to the buddy system;

stop

@enduml