@startuml
title shrink_inactive_list

start

:LIST_HEAD(**folio_list**);
:too_many_isolated();
note left
    It's means other tasks are doing
    reclaim work, so wait for a moment.
end note
:lru_add_drain();
:isolate_lru_folios();
note left
    isolate pages to **folio_list**.
end note
if (no isolate pages ?) then (Yes)
    :return;
    detach
endif

:shrink_folio_list(&**folio_list**);
:move_folios_to_lru(lruvec, &**folio_list**);
note left
    rotate the remaining pages in
    the page_list back to inactive
end note
:lru_note_cost();
:free isolated folios:
* mem_cgroup_uncharge_list(&folio_list)
* free_unref_page_list(&folio_list);

if (stat.nr_unqueued_dirty == nr_taken) then
    :wakeup_flusher_threads(WB_REASON_VMSCAN);
    :wait for write back;
endif
note left
wakeup flusher threads to
write dirty folios back.
end note

:Record reclaim result to sc;

stop

@enduml