@startuml
title shrink_node_memcgs()

start
repeat
:cond_resched();
note left:Avoid soft lockups
:mem_cgroup_calculate_protection;
if (mem_cgroup_below_min()) then (Yes)
    :continue;
    detach
note left:Hard protection
elseif (mem_cgroup_below_low()) then (Yes)
    :skip reclaim;
note left:Soft protection
    :continue;
    detach
endif
:shrink_lruvec();
:shrink_slab();
repeat while (mem_cgroup_iter)

stop

@enduml