@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5

skinparam Component {
    FontSize 200
    FontColor Red
    RoundCorner 10
    BorderThickness 0
    BackgroundColor transparent
    BorderThickness<<text>> 0
    BackgroundColor<<text>> transparent
    FontColor<<box>> transparent
}

component cp [
SCAN_ANON
]
@enduml
