@startuml

skinparam ComponentStyle rectangle
hide stereotype

skinparam Component {
    FontSize 20
    FontColor<<c1>> Red
    BackgroundColor<<c1>> LightGreen
    BackgroundColor<<c2>> LightBlue
}

component "AA" as aa <<c1>>
[BB] <<c2>>

@enduml