@startjson
{
    "free page": "<color:red>**X**",
    "free page": "x",
    "free page": "x",
    "free page": "x",
    "free page": "x",
    "free page": "x",
    "free page": "x",
    "free page": "x",
    "compound page": "x"
}
@endjson