@startuml
skinparam ComponentStyle rectangle
skinparam note {
    BorderColor transparent
    BackgroundColor transparent
}

title table tests

rectangle {
    component "page block" as fp1
    component "page block" as fp2
    component "page block" as fp3
    component "page block" as fp4
    component "page block" as fp5
    component "page block" as fp6

    fp1-down[hidden]-fp2
    fp2-down[hidden]-fp3
    fp3-down[hidden]-fp4
    fp4-down[hidden]-fp5
    fp5-down[hidden]-fp6

    ' note left of [fp1]
    ' zone->end_pfn
    ' end note

    ' note right of [fp1]
    ' cc->free_pfn
    ' end note

    ' note left of [fp6]
    ' zone->start_pfn
    ' end note

    ' note right of [fp6]
    ' cc->migrate_pfn
    ' end note
}

rectangle {
    component " \n\n\n" as p1 #GreenYellow
    component " \n\n\n" as p2
    component " \n\n\n" as p3 #SkyBlue
    component " \n\n\n" as p4
    component " \n\n\n" as p5
    component " \n\n\n" as p6
    component " \n\n\n" as p7
    component " \n\n\n" as p8

    p1-right.p2
    p2-right.p3
    p3-right.p4
    p4-right.p5
    p5-right.p6
    p6-right.p7
    p7-right.p8

    p1-right->p4

}
    p1-down-[Start]
    p8-down-[End]

component shrink_zones() {
    [shrink_node()]
}

[start]-->[shrink_node()]

@enduml