@startuml
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 200
    BackgroundColor LightBlue
    BorderThickness 10
    BorderColor black
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderColor transparent
}

rectangle {
    component p1 [
    page@0x1028000\t
    ====
    ._mapcount = -1
    ====
    .private = 0
    ====
    .index = 0
    ====
    .count = 1
    ]

    component p2 [
    page@0x1029000\t
    ]

    p1-down[hidden]-p2
}

@enduml