@startuml
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 200
    BackgroundColor LightGreen
    BorderThickness 10
    BorderColor black
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderColor transparent
}

rectangle {
    component p1 [
    page@0x1020000\t
    ====
    ._mapcount = -128
    ====
    .private = 2
    ====
    .index = 1
    ====
    .count = 0
    ]

    component p2 [
    page@0x1021000\t
    ]

    component p3 [
    page@0x1022000\t
    ]

    component p4 [
    page@0x1023000\t
    ]

    p1-down[hidden]-p2
    p2-down[hidden]-p3
    p3-down[hidden]-p4
}

@enduml