@startuml
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 200
    BackgroundColor LightBlue
    BorderThickness 10
    BorderColor black
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderColor transparent
}

rectangle {
    component p1 [
    page@0x1024000\t
    ====
    ._mapcount = -1
    ====
    .private = 0
    ====
    .index = 0
    ====
    .count = 1
    ]

    component p2 [
    page@0x1025000\t
    ]

    component p3 [
    page@0x1026000\t
    ]

    component p4 [
    page@0x1027000\t
    ]

    p1-down[hidden]-p2
    p2-down[hidden]-p3
    p3-down[hidden]-p4
}

@enduml