@startuml
title create_cache

start

:s = kmem_cache_zalloc(...);
note left
kmem_cache and kmem_cache_node manager
already created during kmem_cache_init
stage.
end note
:fill basic info in s;
:__kmem_cache_create(s);
:list_add to global slab_caches;

stop

@enduml