@startuml
scale 1/1
left to right direction
skinparam Component {
    FontSize 20
    BorderThickness 1
}
skinparam ComponentStyle rectangle
skinparam Package {
    FontSize 20
    BorderThickness 0
}

package "File Mapping" #LightBlue {
    component "file page" as fp1 #GreenYellow
    component "file page" as fp2 #GreenYellow
    component "inode" as in1 #LightYellow
    component "prio_tree" as pt1 #LightYellow
    component "vma" as v1 #LightYellow
    component "vma" as v2 #LightYellow
    component "vma" as v3 #LightYellow

    [fp1]----->[in1]
    [fp2]----->[in1]
    [in1]---->[pt1]
    [pt1]---->[v1]
    [v1].left.[v2]
    [v2].left.[v3]
}

@enduml