@startuml
scale 1/1
left to right direction
skinparam Component {
    FontSize 20
    BorderThickness 1
}
skinparam ComponentStyle rectangle
skinparam Package {
    FontSize 20
    BorderThickness 0
}

package "KSM Mapping" #LightBlue {
    component "ksm page" as kp1 #GreenYellow
    component "anon vma" as av1 #LightYellow
    component "anon vma" as av2 #LightYellow
    component "anon vma" as av3 #LightYellow
    component "vma" as v1 #LightYellow
    component "vma" as v2 #LightYellow
    component "vma" as v3 #LightYellow
    component "rmap_item" as r1 #LightYellow
    component "rmap_item" as r2 #LightYellow
    component "rmap_item" as r3 #LightYellow

    [kp1]---->[r1]
    [r1].left.[r2]
    [r2].left.[r3]
    [r1]---->[av1]
    [r2]---->[av2]
    [r3]---->[av3]
    [av1]---->[v1]
    [av2]---->[v2]
    [av3]---->[v3]
}

@enduml