@startuml

skinparam ComponentStyle rectangle
hide stereotype
top to bottom direction
scale 2/1

skinparam Component {
    FontSize 20
    FontColor black
    RoundCorner 10
    BorderThickness 1.2
    BackgroundColor transparent
}

skinparam Package {
    FontSize 20
    FontColor black
    RoundCorner 10
    BorderThickness 0
    BackgroundColor transparent
}

package "shrinker" as p1 {
    component xxx [
        | (*count_objects) | |
        | (*scan_objects) | |
        | flags | |
        | list | |
        | id | 1 |
        | *nr_deferred | |
    ]
}
@enduml
