@startuml
scale 2/1

:alloc_pages_current();
if (!in_interrupt() &&\n!(gfp & __GFP_THISNODE)) then (Yes)
    :get_task_policy();
endif
if (MPOL_INTERLEAVE) then (Yes)
    :alloc_page_interleave();
else (No)
    :__alloc_pages_nodemask();
endif
:return page;

@enduml