@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5

skinparam Component {
    FontSize 200
    FontColor black
    BorderThickness 10
    BackgroundColor transparent
}


skinparam Card {
    FontSize 0
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}


skinparam Package {
    FontSize 200
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}


skinparam Rectangle {
    FontSize 200
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}

package "activate_page()" as pack_name {
' component:
component "  activate_page_pvecs  " as c0 #LightBlue
' layout:
}

@enduml
