@startuml

scale 1/5
skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 200
    BackgroundColor transparent
    BorderThickness 10
    BorderColor black
}

skinparam Rectangle {
    FontSize 200
    BackgroundColor transparent
    BorderThickness 0
}

component "\n  **ZONE Allocator**  \n" as c2 #LightYellow


@enduml