@startuml
skinparam ComponentStyle rectangle
skinparam ComponentFontSize 20
skinparam Rectangle {
    BorderColor transparent
    FontColor transparent
    FontSize 0
}

title order pages

card "order=0" as r1 {
    component "P\nA\nG\nE" as p1 #Grey
}
card "order=0" as r2 {
    component "P\nA\nG\nE" as p2 #GreenYellow
}
card "order=1" as r3 {
    component "P\nA\nG\nE" as p3 #GreenYellow
    component "P\nA\nG\nE" as p4 #GreenYellow
}

card "order=2" as r4 {
    component "P\nA\nG\nE" as p5 #GreenYellow
    component "P\nA\nG\nE" as p6 #GreenYellow
    component "P\nA\nG\nE" as p7 #GreenYellow
    component "P\nA\nG\nE" as p8 #GreenYellow
}

card "order=1" as r5 {
    component "P\nA\nG\nE" as p9 #Grey
    component "P\nA\nG\nE" as p10 #Grey
}
card "order=0" as r6 {
    component "P\nA\nG\nE" as p11 #GreenYellow
}
card "order=0" as r7 {
    component "P\nA\nG\nE" as p12 #GreenYellow
}

p1-right[hidden].p2
p2-right[hidden].p3
p3-right[hidden].p4
p4-right[hidden].p5
p5-right[hidden].p6
p6-right[hidden].p7
p7-right[hidden].p8
p8-right[hidden].p9
p9-right[hidden].p10
p10-right[hidden].p11
p11-right[hidden].p12

@enduml