@startuml
title  cma_activate_area()

start
:cma->bitmap = bitmap_zalloc();
:zone = page_zone(pfn_to_page(base_pfn));
while (pfn = base_pfn + 1;\npfn < base_pfn + cma->count;\npfn++)
    if (page_zone(pfn_to_page(pfn)) != zone)
        :goto not_in_zone;<<output>>
        note left
            alloc_contig_range() requires the pfn range
            specified to be in the same zone. Simplify
            by forcing the entire CMA resv range to be
            in the same zone.
        end note
        detach
    endif
endwhile

while (pfn = base_pfn;\npfn < base_pfn + cma->count;\npfn += pageblock_nr_pages)
	:init_cma_reserved_pageblock(pfn_to_page(pfn));
    note left
        Free whole pageblock and
        set its migration type to
        MIGRATE_CMA.
    end note
endwhile
:spin_lock_init(&cma->lock);
:not_in_zone;<<input>>
:out_error;<<input>>
:do clean work;
:return;

stop

@enduml