@startuml
scale 1/5

skinparam Component {
    Style rectangle
    FontSize 200
    BorderThickness 10
    BackgroundColor transparent
}


skinparam Rectangle {
    Style rectangle
    FontSize 200
    BorderThickness 0
    BackgroundColor transparent
}

rectangle r0 {
	' components
	component "  LRU Pages\t\t\t" as r0_c0
	component "  lruvec.lists[]\t\t\t\t" as r0_c1
	' layout
	r0_c0-right[hidden]-r0_c1
}

rectangle r1 {
	' components
	component "  HugeTLBFS Pages\t" as r1_c0
	rectangle "  b_dev_info\t\t\t\t\t" as r1_c1
	' layout
	r1_c0-right[hidden]-r1_c1
}

rectangle r2 {
	' components
	component "  Balloon Pages\t\t" as r2_c0
	component "  hstates[].pages\t\t\t" as r2_c1
	' layout
	r2_c0-right[hidden]-r2_c1
}

rectangle r3 {
	' components
	component "  Buddy System\t\t" as r3_c0
	component "  free_area[].free_list[]\t" as r3_c1
	' layout
	r3_c0-right[hidden]-r3_c1
}

r0-down[hidden]-r1
r1-down[hidden]-r2
r2-down[hidden]-r3
@enduml

