@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5

skinparam Component {
    FontSize 200
    FontColor black
    BorderThickness 0
    BackgroundColor transparent
}

component cp [
<color:red>workingset_size</color> >= <color:blue>refault distance</color>
]
@enduml
