@startuml
title isolate_lru_folios

start

:LIST_HEAD(folios_skipped);

while ()
:fetch folio;
:account total scan pages;
:skip exceed zone pages;
note left
sc->reclaim_idx assigned
in shrink_zones
end note
endwhile
:;
note left
Do not count skipped folios because
that makes the function return with
no isolated folios if the LRU mostly
contains ineligible folios.  This
causes the VM to not reclaim any
folios, triggering a premature OOM.
Account all pages in a folio.
end note
:;
note left
Splice any skipped folios to the start
of the LRU list. Note that this disrupts
the LRU order when reclaiming for lower
zones but we cannot splice to the tail.
If we did then the SWAP_CLUSTER_MAX
scanning would soon rescan the same folios
to skip and waste lots of cpu cycles.
end note
stop

@enduml