@startuml
title LRU Staff

package "lru list and cache" {
    object lru_add {
        add a page to a pagevec
    }

    object pagevec_space {
    }

    object lru_cache_add {
        add a page to a page list
    }

    object __pagevec_lru_add {
    }

    object pagevec_lru_move_fn {
    }

    object __pagevec_lru_add_fn {
    }

    lru_add-->pagevec_space
    lru_cache_add-->lru_add

    lru_cache_add-->__pagevec_lru_add
    __pagevec_lru_add-->pagevec_lru_move_fn
    __pagevec_lru_add-->__pagevec_lru_add_fn

}

package "lru file" {
    object deactivate_file_page {
        forcefully deactivate a file page
    }

    object lru_deactivate_file_fn {
    }

    deactivate_file_page-->lru_deactivate_file_fn
}

package "lru page" {
    object deactivate_page {
    }

    object deactivate_fn {
    }

    deactivate_page-->deactivate_fn
}

package "lru lazyfree" {
    object mark_page_lazyfree {
    }

    object lru_lazyfree_fn {
    }

    mark_page_lazyfree-->lru_lazyfree_fn
}

package "lru rotate" {
    object rotate_reclaimable_page {
    }
}



@enduml