@startuml
title prepare_scan_count

start

if (lru_gen_enabled()) then (Yes)
    :return;
    detach
endif
note left
when CONFIG_LRU_GEN enabled
end note
:mem_cgroup_flush_stats();
:update sc->{anon_cost,file_cost};
note left
Determine the scan balance
between anon and file LRUs
end note

if (sc->force_deactivate) then (Yes)
:set both DEACTIVATE_ANON
& DEACTIVATE_FILE;
else (No)
:set DEACTIVATE_ANON when need;
:set DEACTIVATE_FILE when need;
endif
:reclaim inactivate file pages first;
:reclaim anon pages at last;
note left
when sc->file_is_tiny, means
The file folios on the current
node are dangerously low, so let's
try to reclaim anon pages.
end note

stop

@enduml