@startuml
scale 1/5

skinparam Component {
    Style rectangle
    FontSize 200
    BorderThickness 10
    BackgroundColor transparent
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderThickness 0
}

rectangle {
    component "  4K  " as 4k
    component "\torder=0\t" as order
    [4k]-right[hidden]-[order]

}

@enduml