@startuml

skinparam ComponentStyle rectangle
skinparam Component {
    FontSize 200
    BackgroundColor LightBlue
    BorderThickness 10
    BorderColor black
}

skinparam Rectangle {
    BackgroundColor transparent
    BorderColor transparent
}

component "PAGE" as p1

@enduml