@startuml
!$font_size = 40
skinparam Component {
    FontSize $font_size
    BorderThickness 1.2
    Style rectangle
}

skinparam Rectangle {
    BorderThickness 0
}

scale 2/1
component "steal_suitable_fallback()" as c2

@enduml