@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/1

skinparam Component {
    FontSize 40
    FontColor black
    BorderThickness 1.5
    BackgroundColor transparent
}

' components:
component "__pagevec_lru_add_fn()" as c0 #LightYellow
component "pagevec_move_tail_fn()" as c1 #LightYellow
component "lru_deactivate_file_fn()" as c2 #LightYellow
component "lru_lazyfree_fn()" as c3 #LightYellow
component "__activate_page()" as c4 #LightYellow
' layout:
c0-down[hidden]---c1
c1-down[hidden]---c2
c2-down[hidden]---c3
c3-down[hidden]---c4

@enduml
