@startuml

skinparam ComponentStyle rectangle
hide stereotype
scale 1/5

skinparam Component {
    FontSize 200
    FontColor Blue
    BorderThickness 0
    BackgroundColor transparent
}

component "PGSTEAL_KSWAPD" as cp

@enduml
