@startuml
'skinparam BackgroundColor transparent
skinparam ArrowColor red
skinparam ArrowThickness 2
skinparam PackageStyle rectangle
skinparam ComponentStyle rectangle
skinparam linetype ortho
'left to right direction

package "**kmem_cache**" as kmem_cache {
    [cpu_slab]-right->kmem_cache_cpu0
    [cpu_slab]-right->kmem_cache_cpu1
    [cpu_slab]-right->kmem_cache_cpuN

    component block1 [
        flags
        --
        min_partial
        --
        size
        --
        object_size
    ]
    component block2 [
        offset
        --
        oo
        --
        max
        --
        min
    ]
    component block3 [
        refcount
        --
        name = "xxx"
        --
        list
    ]
    [cpu_slab]-[hidden]-[block1]
    [block1]-[hidden]-[block2]
    [block2]-[hidden]-[block3]
    [block3]-[hidden]-[node]

    [node]-right->kmem_cache_node0
    [node]-right->kmem_cache_node1
    [node]-right->kmem_cache_nodeN

}

package cpu0 #orange {
    package "**kmem_cache_cpu**" as kmem_cache_cpu0 {
        [freelist] #SeaGreen
        [tid]
        [slab]-->slab_slab
        [partial]-->slab_partial
    }
}

package "**slabs**" as slab_slab {
    component "slab" as slab0
    component "slab" as slab1
    component "slab" as slab2
    component "slab" as slab3
    slab0-[hidden]>slab1
}

package "**slabs**" as slab_partial {
    component "slab" as slab4
    component "slab" as slab5
    component "slab" as slab6
    component "slab" as slab7
    slab4-[hidden]>slab5
}

package cpu1 {
    package "**kmem_cache_cpu**" as kmem_cache_cpu1 {
    }
}

package cpuN {
    package "**kmem_cache_cpu**" as kmem_cache_cpuN {
    }
}

package "node[0]" as node0 {
    package "**slabs**" as slab_partial0 {
        component "slab" as slab8
        component "slab" as slab9
        component "slab" as slab10
        component "slab" as slab11
        slab8-[hidden]>slab9
    }

    package "**kmem_cache_node**" as kmem_cache_node0 {
        component "nr_partial" as nr_partial0
        component "partial" as partial0
    }

    partial0-->slab_partial0
    slab_partial0-[hidden]-kmem_cache_node0
}

package "node[1]" as node1 {
    package "**kmem_cache_node**" as kmem_cache_node1 {
    }
}

package "node[N]" as nodeN {
    package "**kmem_cache_node**" as kmem_cache_nodeN {
    }
}

@endluml